/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const acceptHMRUpdate: typeof import('pinia')['acceptHMRUpdate']
  const createPinia: typeof import('pinia')['createPinia']
  const defineStore: typeof import('pinia')['defineStore']
  const getActivePinia: typeof import('pinia')['getActivePinia']
  const getSatusColor: typeof import('../stores/helps')['getSatusColor']
  const mapActions: typeof import('pinia')['mapActions']
  const mapGetters: typeof import('pinia')['mapGetters']
  const mapState: typeof import('pinia')['mapState']
  const mapStores: typeof import('pinia')['mapStores']
  const mapWritableState: typeof import('pinia')['mapWritableState']
  const setActivePinia: typeof import('pinia')['setActivePinia']
  const setMapStoreSuffix: typeof import('pinia')['setMapStoreSuffix']
  const storeToRefs: typeof import('pinia')['storeToRefs']
  const useAppStore: typeof import('../stores/useAppStore')['useAppStore']
  const useDialog: typeof import('naive-ui')['useDialog']
  const useI18n: typeof import('vue-i18n')['useI18n']
  const useLoadingBar: typeof import('naive-ui')['useLoadingBar']
  const useMessage: typeof import('naive-ui')['useMessage']
  const useNotification: typeof import('naive-ui')['useNotification']
}
// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface ComponentCustomProperties {
    readonly acceptHMRUpdate: UnwrapRef<typeof import('pinia')['acceptHMRUpdate']>
    readonly createPinia: UnwrapRef<typeof import('pinia')['createPinia']>
    readonly defineStore: UnwrapRef<typeof import('pinia')['defineStore']>
    readonly getActivePinia: UnwrapRef<typeof import('pinia')['getActivePinia']>
    readonly getSatusColor: UnwrapRef<typeof import('../stores/helps')['getSatusColor']>
    readonly mapActions: UnwrapRef<typeof import('pinia')['mapActions']>
    readonly mapGetters: UnwrapRef<typeof import('pinia')['mapGetters']>
    readonly mapState: UnwrapRef<typeof import('pinia')['mapState']>
    readonly mapStores: UnwrapRef<typeof import('pinia')['mapStores']>
    readonly mapWritableState: UnwrapRef<typeof import('pinia')['mapWritableState']>
    readonly setActivePinia: UnwrapRef<typeof import('pinia')['setActivePinia']>
    readonly setMapStoreSuffix: UnwrapRef<typeof import('pinia')['setMapStoreSuffix']>
    readonly storeToRefs: UnwrapRef<typeof import('pinia')['storeToRefs']>
    readonly useAppStore: UnwrapRef<typeof import('../stores/useAppStore')['useAppStore']>
    readonly useDialog: UnwrapRef<typeof import('naive-ui')['useDialog']>
    readonly useI18n: UnwrapRef<typeof import('vue-i18n')['useI18n']>
    readonly useLoadingBar: UnwrapRef<typeof import('naive-ui')['useLoadingBar']>
    readonly useMessage: UnwrapRef<typeof import('naive-ui')['useMessage']>
    readonly useNotification: UnwrapRef<typeof import('naive-ui')['useNotification']>
  }
}
